### PR TITLE
[Cleanup] Infer types and parameters

### PR DESCRIPTION
**Pull request by BasThomas**

### CODE REVIEW

**Comment by SD10** [comment]
@BasThomas Are you manually linting this or is there a better way? 😁

**Comment by BasThomas** [comment]
Manual!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
I'm gonna try to land #1674 first, might have a couple conflicts

**Comment by BasThomas** [comment]
Should be good to go now!

**Pull request merged**
