### PR TITLE
Move dropdown control to own lib

### LINKED ISSUE #2331: Navigation bar title not displaying properly
Could be related to my previous post #2329 but it seems the label size for navigation bar is small.

GitHawk Upload by Huddie

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

### PR DESCRIPTION
**Pull request by rnystrom**
Fixes #2331 

Lots of screenshot tests to make sure this is fixed. Moved to a horizontal+vertical `UIStackView`. Works great.

https://github.com/GitHawkApp/DropdownTitleView/tree/master/Tests/snapshots/Snap/SnapshotTests

### CODE REVIEW

**Comment by rnystrom** [comment]
simulator screen shot - iphone xs - 2018-10-21 at 15 07 49

**Comment by Huddie** [comment]
@rnystrom is that snapshot showing it working properly? Or not properly? I’m guessing not proper 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@Huddie what do you mean?

**Comment by BasThomas** [comment]
Probably centered between the two `UIBarButtonItem`s flanking it?

**Comment by rnystrom** [comment]
Ya i thought that was the way the nav bar laid things out, tho looking at master, the old header is still centered.

I’ll take a look.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
@BasThomas my thoughts exactly. Wasn’t sure if that was on purpose though or not.
@rnystrom I personally like the centered

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
