### PR TITLE
Fix settings image tint and add external icon to access

### PR DESCRIPTION
**Pull request by rnystrom**
https://stackoverflow.com/questions/41121425/uiimageview-doesnt-always-tint-template-image/45388397

Were there issues for this?

### CODE REVIEW

**Comment by Huddie** [comment]
#2055 ??

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystromtest** [comment]
@Huddie that’s the one

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@Huddie that’s the one

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
😃

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
