### PR TITLE
Retain bookmark order when syncing

### LINKED ISSUE #2537: Stray oddities from bookmark refactor/iCloud integration
Relating to #2483 bookmark refactor, we’ve seen cases where bookmarks are:

1) losing prior ordering
2) new bookmarks add to bottom , not top of list (if intended, 👌, just curious if you intentionally wanted to reverse that)
3) lost bookmarks-perhaps mostly coinciding with private repos

### PR DESCRIPTION
**Pull request by rnystrom**
Fixes #2537

### CODE REVIEW

**Comment by ijm8710** [comment]
Thank you Ryan! You’re the best!

**Comment by ijm8710** [comment]
@rnystrom did this hit the build you just pushed? Must we do AppStore overwrite then Tf, since the order didn’t sync when I just updated a second ago

**Comment by rnystrom** [comment]
Yup need to update from an old version again

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
@rnystrom the orders not syncing over from the App Store version (just did a double-install on top)

**Comment by ijm8710** [comment]
Hey Ryan just hoping you can give this another look when you get a chance before 1.26 public is pushed and we lose ability to revert

**Comment by rnystrom** [comment]
To test this:

- On a TF version, un-bookmark everything so the iCloud store is empty
- Install App Store version
- Bookmark a few things (take a screenshot to remember order)
- Install TF version
- Check that bookmarks exist and are in order

**Comment by ijm8710** [comment]
Thanks Ryan; looks like it does sync if you unbookmark everything first, I had just kept what was there thinking it would merge/overwrite.

The bookmark refactor does place newest bookmarked items at bottom though so my newest item pre-refactor and next item added since are added at opposite ends of list.

I also noticed search is gone as well.

Not sure if those are intentional design changes, unintentional, or temporary as you expand upon the refactor now. 

Ideally I’d still love just a simple count to reflect how many bookmarks you have in the header bar, ability to reorder the bookmarks and some other items I had aggregated in #2376 but are now stray tickets.

**Comment by ijm8710** [comment]
@rnystrom did you have a chance to look at the above comment. One of the things I mentioned:

Old behavior : new bookmarks populate at top
Current behavior: new bookmarks populate at bottom 

The old behavior makes more sense. But if this was an intentional change, it creates a non continuous feed of bookmarks whereby you have relatively new bookmarks at the top (the newest pre bookmark refactor), but the absolute newest bookmarks at the bottom

**Pull request merged**
