### PR TITLE
Adds loading on send

### PR DESCRIPTION
**Pull request by Huddie**
Addresses #2154 

Not sure why "Something went wrong" but it worked. My additions shouldn’t change anything in networking.

### CODE REVIEW

**Comment by rnystrom** [comment]
@Huddie could you add a gif of this working? Traveling atm and can’t try this out. Great idea btw 😍

Eventually I’d love to start saving comments to disk when they error too, with a retry policy. Maybe integrate GitHub API status with the networking layer...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Ya I’ll take a screencast on my phone. That sounds cool on the networking side. Not sure why I was getting an error for sending though. Only seemed to happen when I tried to comment on GitHawk stuff

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Gonna just merge and we can all try it out on TestFlight 😄

**Comment by Huddie** [comment]
Well I’m excited! Please let me know what I can fix if anything comes up!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@Huddie working great for me, good work!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Thanks! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
