### PR TITLE
Settings cell textColor

### PR DESCRIPTION
**Pull request by Huddie**
Set to custom to match the rest of settings 😀

### CODE REVIEW

**Comment by viktorgardart** [comment]
While you're at it, could you also fix the textColor of the "Double Tap Reaction" value label? 
It's currently black when it says "Off" 👍

**Comment by Huddie** [comment]
@viktorgardart that’s a good point

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Any ideas why "Enabled" under Double Tap Reaction is a different font? Everything seems the same to me. 
Cell - StyledTextCell
TextColor - Custom
Font - System 16

**Comment by rnystrom** [comment]
@Huddie nope, can we standardize that one too?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
@rnystrom Ya! But I was a bit confused because it seems to be exactly like the others. Same font, cell, color. Not sure why it’s different but I’ll check it out more

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
I didn't realize they inherited a class called SettingsLabel 😊

**Comment by Huddie** [comment]
@rnystrom Should be good to go

**Pull request merged**
