### PR TITLE
Cut version 1.23.0

### PR DESCRIPTION
**Pull request by rnystrom**

### CODE REVIEW

**Comment by ijm8710** [comment]
Hey what’s the 411 of this new build

**Comment by rnystrom** [comment]
@ijm8710 I'll have to comb the commits for release notes, but looks like Push Notifications are the huge new feature. Other than that lots of UI/UX improvements & fixes.

**Comment by ijm8710** [comment]
Ah I just meant the newest beta build. Where it mentioned updating routing for improved push notifications. I was wondering is that more under the hood or anything we would notice in terms of how soon they come or how they function

**Comment by rnystrom** [comment]
Under the hood

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
