### PR TITLE
[WIP] Activity Indicator color based on background

### PR DESCRIPTION
**Pull request by Huddie**
This was something I had used in an app for status bar color. I adopted it for the activity indicator

Basic idea is:
Replace startAnimating() with startAnimatingOn(color: )

The indicator will then check the color passed in, and set the spinner color accordingly

### CODE REVIEW

**Comment by Huddie** [comment]
Test with labelViewController

**Comment by Huddie** [comment]
I gotta change this title lol 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
@rnystrom Is there any interest for something like this is manually setting it for each view is prefered for quality assurence reasons?

**Comment by Huddie** [comment]
@BrianLitwin Oh I like that idea!

**Comment by rnystrom** [comment]
IMO this is too much magic. I'd much rather be explicit about the colors.

**Comment by Huddie** [comment]
Sounds good

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request closed without merging**
