### PR TITLE
Increase hit area for inbox buttons

### LINKED ISSUE #2721: Difficult to tap small buttons on inbox items
I tried tapping the tiny mute button a few times and always ended up in the issue. 

I have to be very precise when tapping. 

Please can the hit area be enlarged?

GitHawk Upload by gingerbeardman

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.28.0 (1554002345)
Device: iPhone 6s (iOS 12.2)
TestFlight: true
</pre>
</details>

### PR DESCRIPTION
**Pull request by akarataev**
This PR fixed #2721 
I've fixed inbox buttons layout:

Layout

### CODE REVIEW

**Comment by Huddie** [comment]
Well done 👌

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gingerbeardman** [comment]
Super neat changes :)

**Comment by BasThomas** [comment]
Awesome, @akarataev – do you want to add a changelog entry?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akarataev** [comment]
@BasThomas hello,

I'm not against. Do I need to send a PR right [here](https://github.com/GitHawkApp/Release-Notes/blob/master/versions/1.28.0.md)?

**Pull request merged**
