### PR TITLE
New Bookmarks feature that syncs to iCloud

### LINKED ISSUE #2379: Bookmarks show all issues in blue regardless of if issue was open or closed
Is this intentional to not reflect from the list whether they are in an open or closed state?

### PR DESCRIPTION
**Pull request by rnystrom**
- Migrate old `Bookmark` models from `BookmarkStore` to new storage using only the GraphQL node `id` in iCloud's ubiquitous store
  - Take old model, build GraphQL query, find Node `id` for each object, append to new iCloud key store
- Architecture that enables unit testing of VCs
- New UI will fetch objects along w/ status from GraphQL (e.g. issue/PR open+closed+merged)

Much more to come. Putting this up now for early eyeballs.

Fixes #2379, #2377, #702, #683

### CODE REVIEW

**Comment by BasThomas** [comment]
Cool stuff!

**Comment by rnystrom** [comment]
Slowly growing in complexity! Now `RepositoryViewController` loads default branch and issues-enabled when the VC loads. No need to pass that around anymore.

**Comment by rnystrom** [comment]
simulator screen shot - iphone xs - 2018-11-27 at 21 48 53

**Comment by Huddie** [comment]
Looks awesome!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
Yes, dynamic icons for open closed! How about sortable and having a count like bookmarks (7)

**Comment by rnystromtest** [comment]
@ijm8710 lol one thing at a time

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@ijm8710 lol one thing a time

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
Hah what I meant to say was looks awesome...so far :)

**Comment by ijm8710** [comment]
That was a yes like oh yes..haha

**Comment by ijm8710** [comment]
I always hated swipe with the concern that downswiping too fast and at the wrong angle would unintentionally remove one 🤷‍♂️

**Comment by rnystrom** [comment]
@ijm8710 i haven’t forgot about moving either, would like to explore that. I don’t think it’d be too hard, and more valuable than swipe-delete!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
Did anyone’s bookmark order get all out of wack :(

**Comment by ijm8710** [comment]
^did this happen to you as well @rnystrom? Not a complaint; the bkmk refactor is great so far! 

Just curious if the reordering was a) expected b) unlikely to occur again as I might spend a little time removing and adding them back manually to get them in the same order as before as im slightly ocd about that —obv if/once true native reordering comes if that’s still the plan that would be even easier

**Comment by Sherlouk** [comment]
@ijm8710 @rnystrom Just updated to latest TF (was a few behind) to have a look at this and yea mine have changed order (though I'm not particularly fussed about that) but also a bunch of my bookmarks have been deleted!

Curious if that's intended too? If it helps I believe some/most were in private/2fa orgs.

Also a nice improvement is that deleted issues/orgs seem to disappear too!

**Comment by rnystrom** [comment]
@Sherlouk ack will take a look at the private repos part and see if there’s an early return parsing results that might have dropped it. Def my biggest concern with this is the migration deletes data.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
What’s also different is new bookmarks add to bottom of list as opposed to top so I feel in addition to reshuffling it essentially reversed the order as well. Reason I brought up ordering is I felt I lost some bookmaks as well and without a total count or a recognizable order it’s hard to pinpoint that

**Comment by BasThomas** [comment]
Feel free to open up an issue for that @ijm8710 :) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
Would you really want separate ticketed for 1) lost order 2) reversed order 3) lost bookmarks?

I would feel it makes a lot more sense to streamline everything related in the same bread, especially if it’s all related to this PR?

**Comment by BasThomas** [comment]
>Would you really want separate tickets for 1) lost order 2) reversed order 3) lost bookmarks?

Yep! This pull request has already been merged and thus not very visible. Small, easy to tackle questions can be answered and seen by more people and then are more easy to implement separately or side-by-side. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
