### PR TITLE
"Try Beta" on Settings

### LINKED ISSUE #430: Add "Try Beta" to Settings
We could upsell how to add yourself as a beta tester in settings. Get more early feedback on stuff. Not sure how to collect emails tho. I've seen the fastlane tools to do this, but it requires a Heroku app. Maybe it just opens Mail.app to email me?

### PR DESCRIPTION
**Pull request by rizwankce**
Adds "Try Beta" cell on Settings screen, On tap opens the testflight invite link in safari.

Closes #430

### CODE REVIEW

**Comment by rizwankce** [comment]
I tried to hide or remove the "Try Beta" cell is the user is already in TF. But the solutions either didn't work or introduce some layout bugs. So far I have tried hiding the cell or removing from superview. Proper solution would be overriding via `cellForRowIndex` or set `minimumHeight` to 0. But it's not future safe as we are playing with index paths on a static table view.

I guess it's okay to show the cell even in TF builds. Clicking on it open safari web page and "start testing" from test light link just opens TF app.

**Comment by Sherlouk** [comment]
@rizwankce We could just open up a super basic UIAlertController saying something like

"You're already using the TestFlight build" etc (and not open the Safari VC)

Can keep the button and not have layout issues, should be easy enough to do with a quick conditional! (See the FLEX setup as an example)

**Comment by rnystrom** [comment]
Ya don't sweat showing the link in TF builds. Also we wouldn't really be able to test it until its in prod anyways.

**Comment by rizwankce** [comment]
@Sherlouk Nice idea! We can probably show a Squawk message as well. I will send a new PR! 👍

**Comment by j-f1** [comment]
Perhaps on TestFlight, the cell should show the current release (1540303812 right now) and open TestFlight when tapped?

**Pull request merged**
