### PR TITLE
Action Controller images

### PR DESCRIPTION
**Pull request by Huddie**
Allows images to be added to the action controller through @BasThomas pod

Requires `pod install`
I just added the code and the pod name in the podfile. I did `pod install` and run to make sure it worked.

### CODE REVIEW

**Comment by Huddie** [comment]
Addresses  #2047
Sure I can add the pod

**Comment by rnystrom** [comment]
@Huddie mind fixing the conflicts?

**Comment by Huddie** [comment]
@rnystrom not at all! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Not ready to merge yet

**Comment by Huddie** [comment]
@rnystrom Okay, I tested it. Should be up and running.

**Pull request merged**
