### PR TITLE
Port to Xcode 9.3

### LINKED ISSUE #1695: Cannot use self inside a super.init function - Xcode 9.3
Pretty sure this is a new Swift 4.1 rule, but code like 

screen shot 2018-04-01 at 9 03 38 am

Doesn't compile anymore

### PR DESCRIPTION
**Pull request by orta**
Fixes #1695 

* Moves the `dataSource` to be public, if people care about it's access control - you're welcome to merge and make your changes ;)
* Hits the "Update to Latest Build Settings" button
* Kills all warnings (`flatMap` ->  `compactMap`, and warning about compilation timing for the time ago (250ms on *one function*, in danger-js with wallaby, my tests can run in that time ) - fixed by making types explicit

### CODE REVIEW

**Comment by orta** [comment]
Manually verified that tests pass BTW, only ones that don't are 

```
        XCTAssertNotEqual(Secrets.GitHub.clientId, "{GITHUBID}")
        XCTAssertNotEqual(Secrets.GitHub.clientSecret, "{GITHUBSECRET}")
        XCTAssertNotEqual(Secrets.Imgur.clientId, "{IMGURID}")
```

**Comment by jdisho** [comment]
Apparently `compactMap` is part of Swift 4.1. 🤔 Never seen it before.

I am just placing this link in case someone has trouble understanding the difference between `flatMap` and `compactMap`
https://useyourloaf.com/blog/replacing-flatmap-with-compactmap/

**Comment by rnystrom** [comment]
@orta hero 🙌

**Comment by BasThomas** [comment]
Thanks @orta! 😀

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Test

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
