### PR TITLE
Show merge icon on inbox

### LINKED ISSUE #2261: Merged icon
Any reason we use the pull request icon colored purple instead of the merged icon ?

Note the proper merged icon is used everywhere (PR/Labels) but inbox/bookmarks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

### PR DESCRIPTION
**Pull request by rnystrom**
Fixes #2261 

simulator screen shot - iphone xs - 2018-11-04 at 21 02 52

### CODE REVIEW

**Comment by Huddie** [comment]
Thank you again! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Extremely small issue, thought it was just me at first but in the screenshot above the cut version one is read but a slightly different background colour to others. 

I've had this but couldn't find exact steps to reproduce. Is this a known issue?

**Comment by Huddie** [comment]
> Extremely small issue, thought it was just me at first but in the screenshot above the cut version one is read but a slightly different background colour to others.
> 
> I've had this but couldn't find exact steps to reproduce. Is this a known issue?
> 
> (sorry to distract from MR contents)

Ya there is an issue about this already. I'll edit this when I find it

**Comment by rnystrom** [comment]
Thanks for flagging @Sherlouk & @Huddie! Hadn't really paid attention but there's definitely something still off w/ the read bg layer.

**Pull request merged**
