### PR TITLE
Fill in missing switch in watch

### PR DESCRIPTION
**Pull request by rnystrom**

### CODE REVIEW

**Comment by BasThomas** [comment]
🤔 could we merge master in before testing / merging maybe to prevent this in the future?

**Comment by BasThomas** [comment]
Ah wait, the merge commit was red. I guess that's enough of an indicator.

**Comment by rnystrom** [comment]
Ya there might be a bug in GitHawk then because it was green and let me merge. Will have to keep an eye out.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
That's right as the branch was not in sync with master. I think you can enable in Settings that a branch has to be in sync with master before merging. The merge commit itself did fail, so everything was as expected.

**Pull request merged**
