### PR TITLE
Add support for vulnerability alerts

### LINKED ISSUE #1776: Support Security Vulnerability notifications
They break the app now, not showing the full list containing any or more of these type of notifications (ref. https://github.com/GitHawkApp/GitHawk/issues/1449#issuecomment-384928051)

Is this something we can be more lenient about in the future? These "corner case" notifications have broken the app before, like with organization invitations (which we just ignore at the moment).

### PR DESCRIPTION
**Pull request by BasThomas**
We can parse these now, but not sure how they end up in the app. Can we test this with the mock json @rnystrom?

Fixes #1776

### CODE REVIEW

**Comment by BasThomas** [comment]
Oh also this does not change the behavior of logging over breaking, which was mentioned in #1776

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
What’s the workspace check?

Also I think just having the tests is good enough.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
>What’s the workspace check? ...

@rnystrom Xcode 9.3

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Weird wonder why I haven’t committed this 🤔 ...

Lmk when this is good to merge

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Probably because it was generated upon opening the (local pod) project's workspace or something.

**Comment by BasThomas** [comment]
I think this is good to go now.

Still not too sure about how this will end up, specifically because the `Identifier` being a `number(0)`.

**Comment by rnystrom** [comment]
@BasThomas seems like something is failing. Mind taking a look?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
I get a "beautiful" error message.

screen shot 2018-05-08 at 08 10 50

**Comment by rnystrom** [comment]
@BasThomas 

```
Failing tests:
	BookmarkViewModelTests.test_bookmarkText_other()
** TEST FAILED **
```

**Pull request merged**
